CREATE DATABASE IF NOT EXISTS manage;
DROP TABLE IF EXISTS users; 
CREATE TABLE users; 

CREATE TABLE users (
  id integer PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT NOW()
);

