GET http://localhost:3000/api/products
Content-Type: application/json 
Authorization:IntcImFsZ1wiOlwiUlMyNTZcIixcInR5cFwiOlwiSldUXCJ9Ig.IntcImp0aVwiOlwiODNhNGQyNTItZmRkMi00MzU0LWFjZjAtYWNkNDllNWUzM2JhXCIsXCJpZFwiOjEsXCJlbWFpbFwiOlwidGVzdEB0ZXN0Lml0XCIsXCJleHBcIjoxNzg0ODgyODA2fSI.TyeyfHrEYssK4JcX9hR7e1B3U5Oaow8M-sS1JcbgHRKfbWPhsrbCrLwEaWpfnogm6BcfSkZUixWzNd0rihB3yVbcMpOa_eoyCsng95Bf7xSQegILbj8_mo7tPXQvXgwOCO-XXK54fojpnIV9fIoEU4a5l2_1bfDW-QY4B5XzJava4MQzjihKFhAfXDN2myhMhNnusrmoceuMRCHEo8u9ezl6SHyLPYSnTQ1QE9uPQsPRI7lPgk9axYLZQKYAhkGnyUkVWOAbDeMPCZhzlA0RmKoZsi1YrFwFy8jQH5kesx9K63ByMK_0heLe2oAg9TvwHKNJMB9JmDJwf2OLiP9NeQ



