POST http://localhost:3000/api/refresh-token 
Content-Type: application/json 

{
    "token":"IntcImFsZ1wiOlwiUlMyNTZcIixcInR5cFwiOlwiSldUXCJ9Ig.IntcImp0aVwiOlwiMTU3NzM0ZDYtODQ1OS00ZmE2LTgwNjctNTIyMWRkYTE2NjliXCIsXCJpZFwiOjEsXCJlbWFpbFwiOlwidGVzdEB0ZXN0Lml0XCIsXCJleHBcIjoxNzg0ODgzMzM4fSI.h_zi6GAm58H0HR1Dqa8z5M-o_G-bee1X8gKCfrcwl-obDsG_HWwVqtwkGESPYmU44SlYvGgoEyBlMsK-Ie9DiEgFwW1cC1gbAz0KOwH9BDreZ7Cfe_Lep9wDJSFlJQRqjNJ8gxY_gokNBjCbgRkX_uiQIBvS9FXE97N1nn70B7_4lHNmg61u8lSulHz9NdGvM7oSmVgQB56cu0wLF9ZXU-UnKc_orIDxIL8XKadgiSiheV-Z0WvieJ1gm5uRTHjNSkgvAfD56kfAmPMpacWBUB_fnHjSBGBaKaz8MhDRH9FsmQacKlOQjSpKYJDrT4TuVaz_dgkho-UFTprQ5pjtMQ"
}